name: clang-format

on:
  push:
    branches: main
    paths:
      - "include/**"
      - "src/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: "."
          extensions: "h,cpp"
          clangFormatVersion: 17
          inplace: true

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: formatting"
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
